# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: J1STAR
email: j.1star.0726@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Hello, SSAFY!</h3><h1>SSAFY.DevJournal</h1><h3>Awesome SSAFY.HAPPY Post for Developers!</h3>Hope you like it!"



baseurl: "/ssafyHappy" # the subpath of your site, e.g. /blog
url: "http://j1star.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  J1STAR

# Build settings
markdown: kramdown
